///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Tue Nov 22 2016 19:48:25]
// Generate from:
//   [github.com/vipally/gogp/examples/gp/functorcmp.gp]
//   [github.com/vipally/gogp/examples/example2/example2.gpg] [person]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file is used to import by other gp files
//it cannot use independently, simulation C++ stl functors

package example2

const (
	CMPLesser = iota //default
	CMPGreater
) //

//cmp object, zero is Lesser
type CmpPerson byte

const (
	CmpPersonLesser  CmpPerson = CMPLesser
	CmpPersonGreater CmpPerson = CMPGreater
)

//create cmp object by name
func CreateCmpPerson(cmpName string) (r CmpPerson) {
	r = CmpPersonLesser.CreateByName(cmpName)
	return
}

//uniformed global function
func (me CmpPerson) F(left, right *Person) (ok bool) {
	switch me {
	case CMPLesser:
		ok = me.less(left, right)
	case CMPGreater:
		ok = me.great(left, right)
	}
	return
}

//Lesser object
func (me CmpPerson) Lesser() CmpPerson { return CMPLesser }

//Greater object
func (me CmpPerson) Greater() CmpPerson { return CMPGreater }

//show as string
func (me CmpPerson) String() (s string) {
	switch me {
	case CMPLesser:
		s = "Lesser"
	case CMPGreater:
		s = "Greater"
	default:
		s = "error cmp value"
	}
	return
}

//create by bool
func (me CmpPerson) CreateByBool(bigFirst bool) (r CmpPerson) {
	if bigFirst {
		r = CMPGreater
	} else {
		r = CMPLesser
	}
	return
}

//create cmp object by name
func (me CmpPerson) CreateByName(cmpName string) (r CmpPerson) {
	switch cmpName {
	case "": //default Lesser
		fallthrough
	case "Lesser":
		r = CMPLesser
	case "Greater":
		r = CMPGreater
	default: //unsupport name
		panic(cmpName)
	}
	return
}

//lesser operation
func (me CmpPerson) less(left, right *Person) (ok bool) {

	ok = left.Less(right)

	return
}

//Greater operation
func (me CmpPerson) great(left, right *Person) (ok bool) {

	ok = right.Less(left)

	return
}
