///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Tue Oct 25 2016 23:01:48]
// Generate from:
//   [github.com/vipally/gogp/examples/stack.gp_int.go]
//   [github.com/vipally/gogp/examples/example.gpg] [stack_int]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file is used to import by other gp files
//it cannot use independently
//simulation C++ stl functors
package examples

type Comparerint interface {
	F(left, right int) bool
}

type ComparerintCreator int

const (
	LESSER_int ComparerintCreator = iota
	GREATER_int
)

func (me ComparerintCreator) Create() (cmp Comparerint) {
	switch me {
	case LESSER_int:
		cmp = Lesserint(0)
	case GREATER_int:
		cmp = Greaterint(0)
	}
	return
}

type Lesserint byte

func (this Lesserint) F(left, right int) (ok bool) {

	ok = left < right

	return
}

type Greaterint byte

func (this Greaterint) F(left, right int) (ok bool) {

	ok = left > right

	return
}
