// This file was auto-generated by [gogp] tool
// Last modify at: [Sat Sep 24 2016 09:59:44]
// Generate from:
//     [github.com/vipally/gogp/examples/example.gp]
//     [github.com/vipally/gogp/examples/example.gpg] [const_str]
// !!!!!!!!!NEVER MODIFY IT MANUALLY!!!!!!!!!

//    CopyRight @Ally Dale 2016. All rights reserved.
//    Author  : Ally Dale(vipally@gmail.com)
//    Blog    : http://blog.csdn.net/vipally
//    Site    : https://github.com/vipally
//    BuildAt : [Sep 21 2016 17:46:58]
//    Version : 0.0.1


//This is an example of using gopg tool for generic-programming
//this is an example of using gopg to define an auto-lock global value with generic type
//it will be realized to real go code by gopg tool through the .gpg file with the same name
package example

import (
	//"sync"
)

//auto locked global value
type AutoLockGblConstStr struct {
	val  string
	//lock sync.RWMutex
}

//new and init a global value
func NewConstStr(val string) *AutoLockGblConstStr{
	p := &AutoLockGblConstStr{}
	p.val = val
	return p
}

//get value, if modify is disable, lock is unneeded
func (me *AutoLockGblConstStr) Get() (r string) {
//	me.lock.RLock()
//	defer me.lock.RUnlock()
	r = me.val
	return
}

//set value, if modify is disable, delete this function
//func (me *AutoLockGblConstStr) Set(val string) (r string) {
//	me.lock.Lock()
//	defer me.lock.Unlock()
//	r = me.val
//	me.val = val
//	return
//}
