///////////////////////////////////////////////////////////////////
//
//    !!!!!!!!!!NEVER MODIFY THIS FILE MANUALLY!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Tue Sep 27 2016 23:50:42]
// Generate from:
//     [github.com/vipally/gogp/examples/example.gp]
//     [github.com/vipally/gogp/examples/example.gpg] [const_u64]
//
//
//    CopyRight 2016 @Ally Dale. All rights reserved.
//    Use of this source code is governed by a GPL3.0-style.
//    License that can be found in the LICENSE file.
//    Author  : Ally Dale(vipally@gmail.com)
//    Blog    : http://blog.csdn.net/vipally
//    Site    : https://github.com/vipally
//    BuildAt : [Sep 27 2016 19:01:55]
//    Version : 2.1.0
///////////////////////////////////////////////////////////////////

//This is an example of using gopg tool for generic-programming
//this is an example of using gopg to define an auto-lock global value with generic type
//it will be realized to real go code by gopg tool through the .gpg file with the same name
package example

import (
	//"sync"
)

//auto locked global value
type AutoLockGblConstU64 struct {
	val  uint64
	//lock sync.RWMutex
}

//new and init a global value
func NewConstU64(val uint64) *AutoLockGblConstU64{
	p := &AutoLockGblConstU64{}
	p.val = val
	return p
}

//get value, if modify is disable, lock is unneeded
func (me *AutoLockGblConstU64) Get() (r uint64) {
//	me.lock.RLock()
//	defer me.lock.RUnlock()
	r = me.val
	return
}

//set value, if modify is disable, delete this function
//func (me *AutoLockGblConstU64) Set(val uint64) (r uint64) {
//	me.lock.Lock()
//	defer me.lock.Unlock()
//	r = me.val
//	me.val = val
//	return
//}
